# Generated by Django 2.1.5 on 2019-03-04 20:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='borrowedbook',
            name='return_date',
            field=models.DateField(default=datetime.date(2019, 3, 11), help_text='If none: default for 7 days'),
        ),
    ]
