# Generated by Django 2.1.5 on 2019-03-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20190304_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.BigIntegerField(unique=True),
        ),
    ]
